<!DOCTYPE html>
<html>
	<head>
		<meta charset='UTF-8'>
		<meta name='author' content='Roman Ondráček'>
		<meta name='robots' content='noindex' />
		<title>Error 500 - Internal Server Error</title>
		<style>
			#error-body { background: white; width: 500px; margin: 70px auto; padding: 10px 20px }
			#error-body h1 { font: bold 47px/1.5 sans-serif; background: none; color: #333; margin: .6em 0 }
			#error-body p { font: 21px/1.5 Georgia,serif; background: none; color: #333; margin: 1.5em 0 }
		</style>
		<link rel='shortcut icon' type='image/x-icon' href='{$basePath}/favicon.ico'>
	</head>
</head>
<body>
	<div id="error-body">
		<h1>Error 500 - Internal Server Error</h1>
		<p>
			We're sorry, but you must try it again later.<br>
			The server encountered an internal error and was unable to complete your request.<br><br>
			Omlouváme se Vám, ale budete to muset zkusit později.<br>
			Server zaznamenal interní chybu a nebyl schopen zpracovat Váš požadavek.
		</p>
	</div>
</body>
</html>
