<h1>Vítejte v administraci, jste přihlášeni jako <?= $jmeno ?></h1>
<div>
    <?php if (!$admin) : ?>
        <p>Hráči do této sekce webu nemají přístup!</p>
    <?php endif ?>
    <table>
        <?php if ($admin) : ?>
            <tr>
                <td><h2>Články</h2></td>
                <td></td>
            </tr>
            <tr>
                <td><a class="green button" style="width:180px" href="clanek">Seznam</a></td>
                <td><a class="red button" style="width:180px" href="clankyEditor">Editor</a></td>
            </tr>
            <tr>
                <td><h2>Stránky</h2></td>
                <td></td>
            </tr>
            <tr>
                <td><a class="green button" style="width:180px" href="stranka">Seznam</a></td>
                <td><a class="red button" style="width:180px" href="strankyEditor">Editor</a></td>
            </tr>
        <?php endif ?>
        <tr>
            <td><h2>Uživatelské nastavení</h2></td>
            <td></td>
        </tr>
        <tr>
            <td><a class="green button" style="width:180px" href="heslo">Změna hesla</a></td>
            <td><a class="red button" style="width:180px" href="administrace/odhlasit">Odhlásit se</a></td>
        </tr>
        <tr>
            <td><?php if ($admin) : ?><a class="orange button" style="width:180px" href="pridejAdmina">Přidej administrátora</a><?php endif ?></td>
            <td></td>
        </tr>
    </table>
</div>