<div class='panel panel-info'>
    <header class='panel-heading'>
        <h1 class='panel-title'><?= $typ ?> administrátora na webu</h1>
    </header>
    <article class='panel-body'>
        <form method='post'>
            <label for='jmeno'>Jméno</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-user' id='jmeno'></span>
                <input type='text' class='form-control' aria-describedby='jmeno' name='jmeno'>
            </div>
            <input type='submit' class='btn btn-default navbar-btn' value='<?= $tlacitko ?>'>
        </form>
    </article>
</div>