<header>Editor článků</header>
<div>
    <form method="post">
        <input type="hidden" name="clanky_id" value="<?= $clanek['clanky_id'] ?>">
        <strong>Titulek</strong><br>
        <input type="text" name="titulek" value="<?= $clanek['titulek'] ?>"><br>
        <strong>URL</strong><br>
        <input type="text" name="url" value="<?= $clanek['url'] ?>"><br>
        <strong>Autor</strong><br>
        <input type="text" name="pridal" value="<?= $clanek['pridal'] ?>"><br>
        <textarea name="obsah"><?= $clanek['obsah'] ?></textarea>
        <input type="submit" value="Uložit článek">
    </form>
    <script type="text/javascript" src="js/tinymce/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea[name=obsah]",
            theme: "modern",
            plugins: [
                "advlist autolink lists link image charmap print preview hr anchor pagebreak",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking save table contextmenu directionality",
                "emoticons template paste textcolor colorpicker textpattern"
            ],
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            toolbar2: "print preview media | forecolor backcolor emoticons",
            image_advtab: true,
            language: 'cs'
        });
    </script>
</div>