<table>
    <?php foreach ($clanky as $clanek) : ?>
        <tr>
            <td>
                <h2><a href="clanek/<?= $clanek['url'] ?>"><?= $clanek['titulek'] ?></a></h2>
                <?= $clanek['obsah'] ?>
                <?php if ($admin) : ?>
                    <br>
                    <a href="clankyEditor/<?= $clanek['url'] ?>">Editovat</a>
                    <a href="clanek/<?= $clanek['url'] ?>/odstranit">Odstranit</a>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>