<?php foreach ($_clanky as $clanek) : ?>
    <h1><a href="clanek/<?= $clanek['url'] ?>"><?= $clanek['titulek'] ?></a></h1>
    <div>
        <?= $clanek['obsah']; ?>
        <?php if ($admin) : ?>
            <br>
            <a href="clankyEditor/<?= $clanek['url'] ?>">Editovat</a>
            <a href="clanek/<?= $clanek['url'] ?>/odstranit">Odstranit</a>
        <?php endif ?>
    </div>
<?php endforeach ?>