<div class='panel panel-info'>
    <header class='panel-heading'><h1 class='panel-title'>Editor stránek</h1></header>
    <article class='panel-body'>
        <form method='post'>
            <input type='hidden' name='stranky_id' value='<?= $stranka['stranky_id'] ?>'>
            <label for='titulek'>Titulek</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-comment' id='url'></span>
                <input type='text' class='form-control' aria-describedby='titulek' name='titulek' value='<?= $stranka['titulek'] ?>'>
            </div>
            <label for='url'>URL</label>
            <div class='input-group'>
                <span class='input-group-addon' id='url'>http://www.aikidoboskovice/</span>
                <input type='text' class='form-control' aria-describedby='url' name='url' value='<?= $stranka['url'] ?>'>
            </div>
            <label for='pridal'>Autor</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-user' id='pridal'></span>
                <input type='text' class='form-control' aria-describedby='pridal' name='pridal' value='<?= $stranka['pridal'] ?>'>
            </div>
            <label for='obsah'>Obsah</label>
            <textarea name='obsah' class='obsah'><?= $stranka['obsah'] ?></textarea>
            <input type='submit' class='btn btn-default navbar-btn' value='Uložit stránku'>
        </form>
        <script type='text/javascript' src='https://tinymce.cachefly.net/4.2/tinymce.min.js'></script>
        <script type='text/javascript'>
            tinymce.init({
                selector: 'textarea[name=obsah]',
                theme: 'modern',
                plugins: [
                    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern'
                ],
                toolbar1: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                toolbar2: 'print preview media | forecolor backcolor emoticons',
                image_advtab: true,
                language_url: '/js/tinymce/langs/cs.js',
                language: 'cs'
            });
        </script>
    </article>
</div>
