<div class='panel panel-info'>
    <header class='panel-heading'><h1 class='panel-title'>Změna hesla</h1></header>
    <article class='panel-body'>
        <form method='post' autocomplete='off'>
            <label for='heslo'>Současné heslo:</label>
            <input type='password' class='form-control' name='heslo'><br>
            <label for='nove_heslo'>Nové heslo</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-lock' id='nove_heslo'></span>
                <input type='password' class='form-control' aria-describedby='nove_heslo' name='nove_heslo'>
            </div>
            <label for='nove_heslo_znovu'>Nové heslo znovu</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-lock' id='nove_heslo_znovu'></span>
                <input type='password' class='form-control' aria-describedby='nove_heslo_znovu' name='nove_heslo_znovu'>
            </div>
            <input type='submit' class='btn btn-default navbar-btn' value='Změnit heslo'>
        </form>
    </article>
</div>
