<header>Změna hesla</header>              
<div>
    <form method="post">
        <strong>Současné heslo:</strong><br>
        <input type="password" name="heslo"><br>
        <strong>Nové heslo</strong><br>
        <input type="password" name="nove_heslo"><br>
        <strong>Nové heslo znovu</strong><br>
        <input type="password" name="nove_heslo_znovu"><br>
        <input type="submit" value="Změnit heslo">
    </form>
</div>