<header class="panel-heading">
    <h1 class="panel-title">Přihlášení do administrace</h1>
</header>              
<article class="panel-body">
    <form method="post">
        <strong>Jméno</strong><br>
        <input type="text" name="jmeno"><br>
        <strong>Heslo</strong><br>
        <input type="password" name="heslo"><br>
        <input type="submit" value="Přihlásit">
    </form>
</article>
<footer class="panel-footer">
    <a href="registrace">Registrujte se, pokud ještě u nás nemáte účet.</a>
</footer>