<header>Profil hráče <?= $jmeno ?></header>
<div>
    <table>
        <tr>
            <td rowspan="3"><img src="http://mc-heads.net/avatar/<?= $jmeno ?>/100.png"></td>
            <td><strong>Jméno: </strong><?= $jmeno ?></td>
        </tr>
        <tr><td><strong>Poslední přihlášení: </strong><?= $lastlogin ?></td></tr>
        <tr><td><strong>Je admin: </strong><?php if ($admin == 1): ?>Ano<?php else : ?>Ne<?php endif; ?></td></tr>
    </table>
</div>