<div class='panel panel-info'>
    <header class='panel-heading'><h1 class='panel-title'>Registrace</h1></header>
    <article class='panel-body'>
        <form method='post' autocomplete='off'>
            <strong>Jméno</strong><br>
            <input type='text' name='jmeno'><br>
            <strong>Heslo</strong><br>
            <input type='password' name='heslo'><br>
            <strong>Heslo znovu</strong><br>
            <input type='password' name='heslo_znovu'><br>
            <strong>Zadejte aktuální rok (antispam)</strong><br>
            <input type='text' name='rok'><br>
            <input type='submit' value='Registrovat' />
        </form>
    </article>
    <footer class='panel-footer'><a href='prihlaseni'>Přihlaste se, pokud již u nás máte účet.</a></footer>
</div>