<header>Registrace</header>>
<div>
    <form method="post">
        <strong>Jméno</strong><br>
        <input type="text" name="jmeno"><br>
        <strong>Heslo</strong><br>
        <input type="password" name="heslo"><br>
        <strong>Heslo znovu</strong><br>
        <input type="password" name="heslo_znovu"><br>
        <strong>Zadejte aktuální rok (antispam)</strong><br>
        <input type="text" name="rok"><br>
        <input type="submit" value="Registrovat" />
    </form>
</div>