<div class='panel panel-info'>
    <header class='panel-heading'><h1 class='panel-title'>Registrace</h1></header>
    <article class='panel-body'>
        <form method='post' autocomplete='off'>
            <label for='jmeno'>Jméno</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-user' id='jmeno'></span>
                <input type='text' class='form-control' aria-describedby='jmeno' name='jmeno'>
            </div>
            <label for='heslo'>Heslo</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-lock' id='heslo'></span>
                <input type='password' class='form-control' aria-describedby='heslo' name='heslo'>
            </div>
            <label for='heslo_znovu'>Heslo znovu</label>
            <div class='input-group'>
                <span class='input-group-addon glyphicon glyphicon-lock' id='heslo_znovu'></span>
                <input type='password' class='form-control' aria-describedby='heslo_znovu' name='heslo_znovu'>
            </div>
            <label for='antispam'>Antispam</label>
            <div class='g-recaptcha' data-sitekey='<?= $sitekey; ?>' id='antispam'></div>
            <script type='text/javascript' src='https://www.google.com/recaptcha/api.js?hl=cs'></script>
            <input type='submit' class='btn btn-default navbar-btn' value='Zaregistrovat se' />
        </form>
    </article>
    <footer class='panel-footer'><a href='prihlaseni'>Přihlaste se, pokud již u nás máte účet.</a></footer>
</div>