<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<title><?= $titulek ?></title>
		<meta name="description" content="<?= $popis ?>" />
		<meta name="keywords" content="<?= $klicova_slova ?>" />
		<link rel="stylesheet" href="style.css" type="text/css"/>
	</head>

	<body>
		<header>
			<h1>DevbookMVC - ukázkový web</h1>
		</header>
		<?php foreach ($zpravy as $zprava) : ?>
			<p class="zprava"><?= $zprava ?></p>
		<?php endforeach ?>
		<nav>
			<ul>
				<li><a href="clanek/uvod">Úvod</a></li>
				<li><a href="clanek">Články</a></li>
				<li><a href="kontakt">Kontakt</a></li>			
			</ul>
		</nav>
		<br clear="both" />
		
		<article>
			<?php $this->kontroler->vypisPohled(); // vložení aktuálního pohledu do šablony ?>
		</article>
		
		<footer>
			<p>Ukázkový tutoriál pro jednoduché MVC z programátorské sociální sítě 
			<a href="http://www.devbook.cz" target="_blank">devbook.cz</a>. <a href="administrace">Administrace</a></p>
		</footer>
	</body>
</html>