<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/" />
        <meta charset="UTF-8" />
        <title><?= $titulek ?></title>
        <link rel="stylesheet" href="style.css" type="text/css"/>
    </head>
    <body>
        <header>
            <h1>CMS</h1>
        </header>
        <?php foreach ($zpravy as $zprava) : ?>
            <p class="zprava"><?= $zprava ?></p>
        <?php endforeach ?>
        <nav>
            <ul>
                <li><a href="clanek/uvod">Úvod</a></li>
                <li><a href="clanek">Články</a></li>
                <li><a href="administrace">Administrace</a></li>			
            </ul>
        </nav>
        <br clear="both" />
        <article>
            <?php $this->kontroler->vypisPohled(); ?>
        </article>
        <footer>
            <p>&copy; 2014 Roman Ondráček</p>
        </footer>
    </body>
</html>