<!DOCTYPE html>
<html lang="cs">    
    <head>
        <base href="/">
        <meta charset="UTF-8">        
        <meta name="author" content="Roman Ondráček">
        <meta name="robots" content="index, follow">
        <meta name="description" content="Web portálu Funparba.eu">
        <meta name="keywords" content="funparba, funparba.eu, minecraft, team speak 3, ts3, servery, Roman Ondráček">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico">        
        <link rel="stylesheet" type="text/css" href="css/styles.css">        
        <link rel="stylesheet" type="text/css" href="css/buttons.css">	         
        <title><?= $titulek ?> FunParba.eu</title>
    </head>    
    <body>        
        <header>          
            <a href="/"><img src="images/logo.png" alt="Funparba.eu"></a>		         
        </header>                              
        <nav>              
            <ul>                
                <li><a href="/">Novinky</a></li>
                <li><a href="servery/">Servery</a></li>
                <li><a href="stranka/kontakty/">Kontakty</a></li>
            </ul>            
        </nav>                       
        <section>           
            <article>
                <?php foreach ($zpravy as $zprava) : ?>
                    <p class="zprava"><?= $zprava ?></p>
                <?php endforeach ?>    
                <?php $this->kontroler->vypisPohled(); ?>            
            </article>            
            <?php require './include/servery.php'; ?>
            <aside>    
                <!--
                <header>Hlasování</header>    
                <div>        
                    <form action="http://czech-craft.eu/vote.php" method="get" target="_blank">        
                        <select name="id">          
                            <option value="4666" selected>Capture the Flag</option>        
                        </select>
                        <input type="text" name="user" placeholder="Sem zadej svůj nick" size="20">
                        <button type="submit">Hlasovat</button>      
                    </form>    
                </div>
                -->
                <header>Profil</header>    
                <div> 
                    <a href="prihlaseni">Přihlásit se</a><br>
                    <a href="administrace">Administrace</a>
                </div>
                <header>Statistika</header>    
                <div> 
                    <strong>Online hráči: </strong><?= $Players . '/' . $Slots; ?><br>
                    <strong>Zaplněno slotů: </strong><?= (integer) ($Players / $Slots * 100); ?> %<br>
                </div>
                <header>Sledujte nás</header>    
                <div>        
                    <a href="https://facebook.com/funparba.eu"><img src="images/icons/facebook.png" alt="Facebook"></a>        
                    <a href="https://youtube.com/gondyk"><img src="images/icons/youtube.png" alt="YouTube"></a>   
                </div>
                <header class="hidden">Servery poskytuje</header>
                <div class="hidden"><img src="http://www.fakaheda.eu/logo/blue_transparent.png" alt="FakaHeda.eu" title="FakaHeda.eu" style="width: 220px;"></div>
            </aside>
            <br style="clear: both">        
        </section>        
        <footer>	                        
            <p>FunParba.Eu © 2014 - Všechna práva vyhrazena.</p>                    
        </footer>    
    </body>
</html>