<h1>Editor stránek</h1>
<div>
    <form method="post">
        <input type="hidden" name="clanky_id" value="<?= $stranka['stranka_id'] ?>">
        <strong>Titulek</strong><br>
        <input type="text" name="titulek" value="<?= $stranka['titulek'] ?>"><br>
        <strong>URL</strong><br>
        <input type="text" name="url" value="<?= $stranka['url'] ?>"><br>
        <textarea name="obsah"><?= $stranka['obsah'] ?></textarea>
        <input type="submit" value="Uložit článek">
    </form>
    <script type="text/javascript" src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "textarea[name=obsah]",
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            entities: "160,nbsp",
            entity_encoding: "named",
            entity_encoding: "raw"
        });
    </script>
</div>