<?php require './include/servery.php'; ?>
<h1>Servery</h1>
<div>
    <table style="width: 100%" class="center">
        <tr>
            <th>Název</th>
            <th>IP</th>
            <th>Status</th>
            <th>Hráči</th>
            <th class="hidden">Verze</th>
            <th class="hidden">Využito</th>
        </tr>
        <tr>
            <td>Lobby</td>
            <td>play.funparba.eu</td>
            <td><?= $Lobby->status; ?></td>
            <td><?= $Lobby->players . "/" . $Lobby->slots ?></td>
            <td class="hidden"><?= $Lobby->version ?></td>
            <td class="hidden"><?= (integer) ($Lobby->players / $Lobby->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>Extreme</td>
            <td>93.91.250.215</td>
            <td><?= $E->status ?></td>
            <td><?= $E->players . "/" . $E->slots ?></td>
            <td class="hidden"><?= $E->version ?></td>
            <td class="hidden"><?= (integer) ($E->players / $E->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>SkyBlock</td>
            <td>sky.funparba.eu</td>
            <td><?= $SB->status ?></td>
            <td><?= $SB->players . "/" . $SB->slots ?></td>
            <td class="hidden"><?= $SB->version ?></td>
            <td class="hidden"><?= (integer) ($SB->players / $SB->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>Creative</td>
            <td>93.91.250.120:27639</td>
            <td><?= $Creative->status ?></td>
            <td><?= $Creative->players . "/" . $Creative->slots ?></td>
            <td class="hidden"><?= $Creative->version ?></td>
            <td class="hidden"><?= (integer) ($Creative->players / $Creative->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>PVP</td>
            <td>play.armycraft.eu</td>
            <td><?= $PVP->status ?></td>
            <td><?= $PVP->players . "/" . $PVP->slots ?></td>
            <td class="hidden"><?= $PVP->version ?></td>
            <td class="hidden"><?= (integer) ($PVP->players / $PVP->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>FutureCraft</td>
            <td>future.funparba.eu</td>
            <td><?= $FC->status ?></td>
            <td><?= $FC->players . "/" . $FC->slots ?></td>
            <td class="hidden"><?= $FC->version ?></td>
            <td class="hidden"><?= (integer) ($FC->players / $FC->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>Team Fortress 2</td>
            <td><a href="steam://connect/217.11.249.93:27554">217.11.249.93:27554</a></td>
            <td><?= $TF2->status ?></td>
            <td><?= $TF2->players . "/" . $TF2->slots ?></td>
            <td class="hidden"></td>
            <td class="hidden"><?= (integer) ($TF2->players / $TF2->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td>Team Speak 3</td>
            <td><a href="ts3server://ts3.funparba.eu">ts3.funparba.eu</a></td>
            <td><?= $TS3->status ?></td>
            <td><?= $TS3->players . "/" . $TS3->slots ?></td>
            <td class="hidden"></td>
            <td class="hidden"><?= (integer) ($TS3->players / $TS3->slots * 100); ?> %</td>
        </tr>
        <tr>
            <td><strong>Celkem</strong></td>
            <td></td>
            <td></td>
            <td><strong><?= $Players . "/" . $Slots ?></strong></td>
            <td class="hidden"></td>
            <td class="hidden"><strong><?= (integer) ($Players / $Slots * 100); ?> %</strong></td>
        </tr>
    </table>
</div>