<header class="panel-heading">
    <h1 class="panel-title"><?= $titulek ?></h1>
</header>
<article class="panel-body"><?= $_obsah ?></article>
<footer class="panel-footer">
    <strong>Napsal <?= $pridal ?> <?= date('j. n. Y, G:i:s', strtotime($pridano)); ?></strong>
    <?php if ($admin) : ?><br><a href="editor/<?= $url ?>">Editovat</a> | <a href="stranka/<?= $url ?>/odstranit">Odstranit</a><?php endif ?>
</footer>